export const CURRENT_XP_CHANGED = 'CURRENT_XP_CHANGED';
export const TARGET_XP_CHANGED = 'TARGET_XP_CHANGED';
export const POKEMON_COUNT_CHANGED = 'POKEMON_COUNT_CHANGED';
export const CANDY_COUNT_CHANGED = 'CANDY_COUNT_CHANGED';
